// Generated by Wrangler by running `wrangler types`

interface Env {
  DB: D1Database;
  WJH_ACCOUNT: string;
  WJH_PASSWORD: string;
  WJH_API: string;
  ZF_PASSWORD: string;
  FEISHU_WEBHOOK: string;
  FEISHU_LOG_WEBHOOK: string;
}
